## 目录

- [异常机制](#异常机制)
- [异常使用实例](#异常使用实例)
- 



## 异常机制

- **异常跨函数.**
- **异常必须处理.**

```c++
/* C++ 14  以及之前的写法
 * 基础语法 , throw value; 抛出一个值.  try { ... }catch {...} catch { ... } 异常接收和处理
 *           返回值 函数名(参数) throw (类型,int,double) { ... }  异常接口声明
 */

// C++ 17之后,就要进行替换, throw(int,float,char)  -> noexcept(false)  不许抛出异常,true则可以
int divide(int x,int y) throw(int,float,char)       // 后面这个 throw 是异常接口声明.
{                       // 显示这个函数只能抛出三种异常,其他的程序就宕掉,就当成给人看的.
        int a ;         // 当抛出异常的时候, 这个在栈上的值会被析构.无论他有没有被使用.
        if( y == 0){            // 因为被除数不能为0 , 所以要判别.
            throw y;            // 发现被除数为0, 通过关键字 throw 抛出异常,跳出函数,回到上层.
        }
        return x/y;             // 如果无异常则正常的返回.
}


void test01(){   // 后面没有throw 表示这个函数可以抛出任何异常.
    try{                    // 下面执行的函数可能会出现异常,使用 try 关键字来接受异常.
        divide(10,0);       // 执行这个函数,      如果上面没有抛出异常,那么就忽略下面.
    }catch(int &e){          // 通过关键字 catch 来捕获异常.e 会得到抛出的值.(类型要匹配)
        cout << "除数为 " << e <<endl;      // 解决方案
    }catch(float &d){        // int的结束, 向下执行.捕获 float 的异常
        cout << "处理float" << endl;     //处理float的异常 
    }catch(...) {           //这里语法特殊有三个点,表示 捕获所有异常,填补上面没有匹配
        cout <<"未知类型异常" <<endl;     // 到的未知异常
    }
}

void stre()  throw (){   // 后面的这个 throw 没有参数,表示这个函数绝对不可以抛出任何异常.
       cout << "这个函数不可以抛出任何异常" <<endl;       
}


class obj{ //这里面拥有一个构造函数.
public:
    obj() {std::cout << "无参构造" << std::endl; p = new int (5);  }
    obj( int a  ) { std::cout << "int构造" << std::endl; p = new int (10); }
    obj( obj& ob  ){ std::cout << "拷贝构造" << std::endl;  this->p = new int(*ob.p); }
    obj(const  obj& ob  ){ std::cout << "拷贝构造" << std::endl;  this->p = new int(*ob.p); }
    obj& operator= (const obj& ob ) { std::cout << " 等 = 号拷贝构造" << std::endl;  this->p = new int(*ob.p); return *this; }
    ~obj( ) { std::cout << "~析构" << std::endl;  if(p) delete p; else  p = nullptr;}
private:
    int *p;
};

void return_class_obj(){   // 该函数和下面的函数一起使用, 下面三行留下一行就可以了.
//    throw obj();  // 普通对象接收 一个匿名对象, 表示抛出一个异常.
//    throw  obj();  // 引用接收    一个匿名对象   (尽量都要使用引用来进行)
//    throw  new obj(); // 指针接收  这里必须new 一个对象,否则会直接被析构,从而调用失败
}
void ming(){
 try{       //下面的三个 catch 异常处理, 只是示范, 只留下最后两种就可以了
    return_class_obj();  //测试生命周期 返回一个类对象,  这里面拥有一个构造函数.
 }catch(obj A){      // 生命周期的顺序是,拷贝构造,异常处理 .catch结束后-析构A,再析构函数抛出的对象.
    cout<< "使用普通元素去接收抛出的异常"<<endl;
 }catch(obj& B){     // 生命周期的顺序是  异常处理 .catch结束后-析构函数抛出的对象.
    cout<< "使用引用去接收抛出的异常"<<endl;
 }catch(obj* C){     // 生命周期的顺序是  异常处理 .catch结束后-析构函数抛出的对象.
    cout<< "使用普通指针元素去接收抛出的异常"<<endl;
    delete C;
 }
}
```

- ==**有的时候抛出的异常没有进行处理,编译也不会出错,但是运行的话会程序会直接崩溃.**==
- **throw 抛出来的异常都是有类型的,可以是数字,字符串,类对象.**
- **throw 的异常是有	类型的, catch 需严格匹配异常类型.**
- ==**当异常接受和处理出问题时, 会得到 abort() 函数抛出的 SIGABRT信号**==
  - **例如: 使用 指针去接收 在另一个函数创建的在栈中的对象, 就会得到这个错误**

> **使用 普通类型元素, 引用, 指针 三种方法接受抛出的异常的时候,这三种生命周期如下:**
>
> - **普通类型元素: 创建一个普通类型元素,拷贝抛出的元素, catch处理完之后就析构,然后析构抛出的元素.**
> - **引用 : 不用创建元素和构造,也不用拷贝,直接异常对象处理,处理之后把抛出的元素析构.**
> - **指针 : 如果是new 的对象返回,那么和引用相同.  如果是一个普通元素返回,要防止这个返回对象提前析构,也就是说 在另一个函数的栈内的对象会被自动析构,导致无法指向**



- ==**如果异常抛到顶层,还没有处理,这个时候程序会挂掉,就是调用 `terminate()` 这个函数来终止程序.**==
- **c++的异常机制会跨函数, 如果抛出一个异常当前函数没有处理函数,那么往回查找,并且逐层析构,直到找到或崩溃.**
- ==**c++的异常必须要处理,绝对不能留下, 一旦没有处理那么程序会直接崩溃.**==
- **异常抛出后,从进入 try 块开始,到异常被抛出前,这期间在栈上构造的所有对象,都会自动析构**
  - **析构的顺序与构造的顺序相反,这一过程称为 栈解旋 (unwinding).**

- **一旦异常抛出,那么他会玩命的往回寻找 catch 定义的捕获他抛出的值的位置,期间经过的所有的在栈上的任何内容都会被析构.**



- **C++17标准新关键字 noexcept**

  - **`noexcept(false)`  不许抛出异常**

  - **`noexcept(true)`  可以抛出异常**

  - ```c++
    void stre  ()  noexcept(false)  //   该函数不许抛出异常
    {         cout << "这个函数不可以抛出任何异常" <<endl;       }
    
    void start(){
      try{
          stre();
      }catch(...){
        exit(1);
      }
    }
    ```

  - 







## 异常使用实例

- **需要引用头文件 `<stdexcept>` 来包含一个异常处理类,多人开发就用这个.**
- **引用头文件之后,再继承这个文件中的异常处理类 `exception`, 并重载 `what()` 来进行异常输出.(还可以添加别的).**

```c++
#include <iostream>
#include <stdexcept>
using namespace std;

class My_out_of_ramge:public exception{
    virtual const char* what() const throw(){   // 必须这么写,不能缺少关键字,否则报错
        return "错误信息";
    }
};

//也可以自己定义异常基类 , 也就是抽象类
class BaseMyException{               // 抽象类接口
public:
	virtual void what() = 0;            // 这是最简单的类了
	virtual ~BaseMyException(){}        // 析构必须写
};

class TargetSpaceNullException:public BaseMyException{  //子函数 继承了基类
public:
	virtual void what(){
		cout << "目标空间为空" << endl;
	}

	~TargetSpaceNullException(){
	}
};

class SourceSpaceNullException:public BaseMyException{  // 子函数  继承了基类
public:
	virtual void what(){
		cout << "源空间空间为空" << endl;
	}
	~SourceSpaceNullException(){
	}
};

void copy_str(char* taget, char* source){   // 拷贝函数, 可以抛出任何异常.
	if(taget == NULL ){
		throw TargetSpaceNullException();
	}
	if(source == NULL){
		throw SourceSpaceNullException();
	}

  *taget = *source;
  while(*source != '\0'){
    source++;
		taget++;
    *taget = *source;
  }
}



int main(void){
	char source[9] = {"abcdefg\0"};
	char buf[1024] = { [0 ... 1023] = '\0' };
	
	try{
		copy_str(buf,source);
	}catch(BaseMyException& e){         // 这里只写抽象类就可以实现多态
		e.what();
	}

	cout << source << endl;
	cout << buf << endl;

	return 0;
}

```

- **在写可能会出现错误的函数的时候 就不要胡乱抛出了, 直接抛出类对象就好了,非常方便, 用多态.**
- **有的地方不允许出现异常抛出,那么要多多注意,把在他前面的所有异常统统搞定就能正确进行了.**
- **函数后面出现 `throw()`  括号里面什么都没有的话,就表示这个函数不允许出现任何的异常抛出.(但可以处理异常).**
- **函数后面出现 `throw(int,char)`  括号里面出现的参数,就表示这个函数有可能会抛出这些类型的异常.**

- **函数后面出现 `const` 表示不允许修改传入的参数.**
- **`try` 中的 `catch()` 的括号内 ,最好传入类型的引用, 这样比较好处理,而且不会犯错,(不要轻易传入指针).**
- **`try` 中的 `catch()` 的括号内, 如果传入的是一个类对象,那么他会调用类的拷贝构造,一定要提前把拷贝和=号都写好.**

